<template>
  <div class="history">
    <div class="history__container">
      <main-title tag="h2" titleName="История платежей">
        <router-link class="history__button" to="/wallets">
          Кошельки
        </router-link>
      </main-title>
      <div class="history__filter">
        <div class="history__filter_block">
          <div class="history__filter_label">Кошелек</div>
          <main-select
            @add-filter="this.filter"
            class="history__filter_select"
            :options="this.walletOptions"
          ></main-select>
        </div>
        <div class="history__filter_block">
          <div class="history__filter_label">Продукт</div>
          <main-select
            @add-filter="this.filter"
            class="history__filter_select"
            :options="this.walletOptions"
          ></main-select>
        </div>
        <div class="history__filter_block">
          <div class="history__filter_label">Тип операции</div>
          <main-select
            @add-filter="this.filter"
            class="history__filter_select"
            :options="this.operationOptions"
          ></main-select>
        </div>
        <div class="history__filter_block">
          <div class="history__filter_label">Дата</div>
          <Datepicker
            v-model="date"
            range
            placeholder="Любая"
            auto-apply
            locale="ru"
            position="center"
            :hide-navigation="['time']"
            :enable-time-picker="false"
          >
            <template #input-icon>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
              >
                <path
                  d="M3 10H21M7 3V5M17 3V5M6.2 21H17.8C18.9201 21 19.4802 21 19.908 20.782C20.2843 20.5903 20.5903 20.2843 20.782 19.908C21 19.4802 21 18.9201 21 17.8V8.2C21 7.07989 21 6.51984 20.782 6.09202C20.5903 5.71569 20.2843 5.40973 19.908 5.21799C19.4802 5 18.9201 5 17.8 5H6.2C5.0799 5 4.51984 5 4.09202 5.21799C3.71569 5.40973 3.40973 5.71569 3.21799 6.09202C3 6.51984 3 7.07989 3 8.2V17.8C3 18.9201 3 19.4802 3.21799 19.908C3.40973 20.2843 3.71569 20.5903 4.09202 20.782C4.51984 21 5.07989 21 6.2 21Z"
                  stroke="#000034"
                  stroke-opacity="0.62"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </template>
          </Datepicker>
        </div>
      </div>
      <main-slider :table="this.historyInfo"></main-slider>
    </div>
  </div>
</template>
<script>
import MainSlider from "@/components/account/MainSlider";
import Datepicker from "@vuepic/vue-datepicker";

export default {
  components: { MainSlider, Datepicker },
  data() {
    return {
      date: {},
      walletOptions: [
        { title: "Любой", value: 1 },
        { title: "Bitcoin", value: 2 },
        { title: "Bitcoin Cash", value: 3 },
        { title: "Litecoin", value: 4 },
      ],
      operationOptions: [
        { title: "Любой", value: 1 },
        { title: "Пополнение", value: 2 },
        { title: "Доход", value: 3 },
        { title: "Вывод", value: 4 },
      ],
      historyInfo: {
        titles: ["Дата", "Кошелек", "Тип операции", "Сумма", "Статус"],
        rows: [
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
          {
            date: "29.11.2022",
            img: "bitcoin_img.png",
            wallet: "Bitcoin",
            type: "Поступление",
            BTC: 0,
            status: "Успешно",
          },
        ],
      },
    };
  },
  mounted() {
    document.title = "История";
  },
};
</script>
<style lang="scss" scoped>
.history {
  .title {
    margin: 54px 0 25px;
    width: 100%;
    display: inline-flex;
  }
  // .history__button
  &__button {
    border-radius: 13px;
    font-weight: 500;
    height: 51px;
    color: #fff;
    background-color: #4182ec;
    margin-left: auto;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    font-size: 20px;
    line-height: 28px;
    min-width: 228px;
    box-shadow: none;
    transform: translate(0, 0);
    transition: all 0.3s ease;
    &:hover {
      box-shadow: 4px 4px rgba(63, 123, 221, 0.27);
      background-color: #4182ec;
      color: #fff;
      transform: translate(-4px, -4px);
    }
  }
  // .history__filter
  &__filter {
    display: flex;
    width: 100%;
    align-items: flex-end;
    margin-bottom: 24px;
    gap: 16px;
    // .history__filter_block
    &_block {
      display: flex;
      flex-direction: column;
      max-width: 100%;
      width: 100%;
    }
    // .history__filter_label
    &_label {
      margin-bottom: 8px;
      font-weight: 400;
      font-size: 16px;
      line-height: 23px;
      color: rgba(0, 0, 0, 0.62);
    }
    // .history__filter_select
    &_select {
      height: 48px;
    }
  }
}
</style>
