export const RouteNamesMap = {
    public: {
        about: "AboutPage",
        home: "HomePage",
        calculator: "CalculatorPage",
        complexity: "ComplexityPage",
        // help: "FaqPage",
        hosting: "HostingPage",
        miners: "MinersPage",
        login: "LoginPage",
        registration: "RegPage",
        confirm: "ConfirmPage",
    },
    profile: {
        accounts: "SubsPage",
        statistic: "StatisticPage",
        connecting: "ConnectingPage",
        income: "IncomePage",
        settings: "SettingsPage",
        wallets: "WalletsPage",
        workers: "WorkersPage",
        watchers: "WatchersPage",
        faq: "FaqPage",
        referral: {
            overview: "OverviewPage",
            "my-referral": "MyReferralPage",
            "earn-rewards": "EarnRewardsPage",
        },
    },
};
