export const ValidationErrorKeysEnum = {
    email: "email",
    max: "max",
    min: "min",
    // limit_length: "limit_length",
    // limit_length_and_letters_and_numbers: "limit_length_and_letters_and_numbers",
    string: "string",
    upper: "upper",
    lower: "lower",
    number: "number",
    string_number: "string_number",
    upper_number: "upper_number",
    lower_number: 'lower_number',
    equal: 'equal',
    required: 'required',
}
