export const ColumnBlackListEnum = {
    class: true,
    graphId: true,
    data: true,
    unit: true,
    unit24: true,
    message: true,
    validate: true,
    group_id: true,
    pending_amount: true,
    reject_percent: true,
    yesterday_amount: true,
    today_forecast: true,
    workers_count_active: true,
    workers_count_in_active: true,
    workers_count_unstable: true,
    last_month_amount: true,
    total_amount: true,
    hash_per_day_unit: true,
    hash_per_min_unit: true,
    hash_per_day: true,
    hash_per_min: true,
    status: true,
    workers_count: true
};
